# python version 1.0						DO NOT EDIT
#
# Generated by smidump version 0.4.8:
#
#   smidump -f python DDM-MGMT-MIB

FILENAME = "Ddm.mib"

MIB = {
    "moduleName" : "DDM-MGMT-MIB",

    "DDM-MGMT-MIB" : {
        "nodetype" : "module",
        "language" : "SMIv2",
        "organization" :    
            """D-Link Corp.""",
        "contact" : 
            """http://support.dlink.com""",
        "description" :
            """The structure of DDM for the proprietary enterprise.""",
        "revisions" : (
            {
                "date" : "1912-08-10 00:00",
                "description" :
                    """[Revision added by libsmi due to a LAST-UPDATED clause.]""",
            },
        ),
        "identity node" : "swDdmMIB",
    },

    "imports" : (
        {"module" : "SNMPv2-TC", "name" : "DisplayString"},
        {"module" : "SNMPv2-SMI", "name" : "MODULE-IDENTITY"},
        {"module" : "SNMPv2-SMI", "name" : "OBJECT-TYPE"},
        {"module" : "SNMP-FRAMEWORK-MIB", "name" : "SnmpAdminString"},
        {"module" : "DLINK-ID-REC-MIB", "name" : "dlink-common-mgmt"},
    ),

    "nodes" : {
        "swDdmMIB" : {
            "nodetype" : "node",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72",
            "status" : "current",
        }, # node
        "swDdmCtrl" : {
            "nodetype" : "node",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.1",
        }, # node
        "swDdmTrapState" : {
            "nodetype" : "scalar",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.1.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "enabled" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "disabled" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                },
            },
            "access" : "readwrite",
            "description" :
                """This object indicates the trap action state.""",
        }, # scalar
        "swDdmLogState" : {
            "nodetype" : "scalar",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.1.2",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "enabled" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "disabled" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                },
            },
            "access" : "readwrite",
            "description" :
                """This object indicates the log action state.""",
        }, # scalar
        "swDdmPowerUnit" : {
            "nodetype" : "scalar",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.1.3",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "mw" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "dbm" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                },
            },
            "access" : "readwrite",
            "default" : "mw",
            "description" :
                """This object indicates the TX/RX power global unit.""",
        }, # scalar
        "swDdmInfo" : {
            "nodetype" : "node",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.2",
        }, # node
        "swDdmStatus" : {
            "nodetype" : "node",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.2.1",
        }, # node
        "swDdmStatusTable" : {
            "nodetype" : "table",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.2.1.1",
            "status" : "current",
            "description" :
                """This table contains the DDM status information.""",
        }, # table
        "swDdmStatusEntry" : {
            "nodetype" : "row",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.2.1.1.1",
            "status" : "current",
            "linkage" : [
                "swDdmPort",
            ],
            "description" :
                """This is an entry of the swDdmStatusTable.""",
        }, # row
        "swDdmPort" : {
            "nodetype" : "column",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.2.1.1.1.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "1",
                        "max" : "65535"
                    },
                    ],
                    "range" : {
                        "min" : "1",
                        "max" : "65535"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """This object indicates the port.""",
        }, # column
        "swDdmTemperature" : {
            "nodetype" : "column",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.2.1.1.1.2",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """This object indicates the real time value of the temperature. As the value 
is a floating point data type, the DisplayString type is used to define this parameter.""",
        }, # column
        "swDdmVoltage" : {
            "nodetype" : "column",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.2.1.1.1.3",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """This object indicates the real time value of the supply voltage. As the value 
value is a floating point data type, the DisplayString type is used to define this parameter.""",
        }, # column
        "swDdmBiasCurrent" : {
            "nodetype" : "column",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.2.1.1.1.4",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """This object indicates the real time value of the tx bias.""",
        }, # column
        "swDdmTxPower" : {
            "nodetype" : "column",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.2.1.1.1.5",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """This object indicates the real time value of the tx power. As the value 
is a floating point data type, the DisplayString type is used to define this parameter.""",
        }, # column
        "swDdmRxPower" : {
            "nodetype" : "column",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.2.1.1.1.6",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """This object indicates the real time value of the rx power. As the value is 
a floating data type, the DisplayString type is used to define this parameter.""",
        }, # column
        "swDdmMgmt" : {
            "nodetype" : "node",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.3",
        }, # node
        "swDdmThresholdMgmt" : {
            "nodetype" : "node",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.3.1",
        }, # node
        "swDdmThresholdMgmtTable" : {
            "nodetype" : "table",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.3.1.1",
            "status" : "current",
            "description" :
                """This table contains DDM temperature configuration information.""",
        }, # table
        "swDdmThresholdMgmtEntry" : {
            "nodetype" : "row",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.3.1.1.1",
            "status" : "current",
            "linkage" : [
                "swDdmPort",
                "swDdmThresholdType",
            ],
            "description" :
                """This is an entry of the swDdmConfigThresholdTable.""",
        }, # row
        "swDdmThresholdType" : {
            "nodetype" : "column",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.3.1.1.1.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "temperature" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "voltage" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                    "bias" : {
                        "nodetype" : "namednumber",
                        "number" : "3"
                    },
                    "txPower" : {
                        "nodetype" : "namednumber",
                        "number" : "4"
                    },
                    "rxPower" : {
                        "nodetype" : "namednumber",
                        "number" : "5"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """This object indicates the threshold type.""",
        }, # column
        "swDdmHighAlarm" : {
            "nodetype" : "column",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.3.1.1.1.2",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readwrite",
            "description" :
                """This object indicates the high alarm threshold value to be configured. As the 
value is a floating point data type, the DisplayString type is used to define this parameter.""",
        }, # column
        "swDdmLowAlarm" : {
            "nodetype" : "column",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.3.1.1.1.3",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readwrite",
            "description" :
                """This object indicates the low alarm threshold value to be configured. As the
value is a floating data type, the DisplayString type is used to define this parameter.""",
        }, # column
        "swDdmHighWarning" : {
            "nodetype" : "column",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.3.1.1.1.4",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readwrite",
            "description" :
                """This object indicates the high warning threshold value to be configured. As 
the value is a floating data type, the DisplayString type is used to define this parameter.""",
        }, # column
        "swDdmLowWarning" : {
            "nodetype" : "column",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.3.1.1.1.5",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readwrite",
            "description" :
                """This object indicates the low warning threshold value to be configured. As 
the value is a floating data type, the DisplayString type is used to define this parameter.""",
        }, # column
        "swDdmActionMgmt" : {
            "nodetype" : "node",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.3.2",
        }, # node
        "swDdmActionMgmtTable" : {
            "nodetype" : "table",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.3.2.1",
            "status" : "obsolete",
            "description" :
                """This table contains the configuration of the action taken 
when any parameter exceeds its threshold.""",
        }, # table
        "swDdmActionMgmtEntry" : {
            "nodetype" : "row",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.3.2.1.1",
            "status" : "obsolete",
            "linkage" : [
                "swDdmPort",
                "swDdmActionType",
            ],
            "description" :
                """This is an entry of the swDdmConfigActionTable.""",
        }, # row
        "swDdmActionType" : {
            "nodetype" : "column",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.3.2.1.1.1",
            "status" : "obsolete",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "alarm" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "warning" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """This object indicates the action type.""",
        }, # column
        "swDdmShutdown" : {
            "nodetype" : "column",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.3.2.1.1.2",
            "status" : "obsolete",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "enabled" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "disabled" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                    "other" : {
                        "nodetype" : "namednumber",
                        "number" : "3"
                    },
                },
            },
            "access" : "readwrite",
            "description" :
                """This object indicates the shutdown action. The 
value 'other' means that the port does not support DDM.""",
        }, # column
        "swDdmTrapAndLog" : {
            "nodetype" : "column",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.3.2.1.1.3",
            "status" : "obsolete",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "enabled" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "disabled" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                    "other" : {
                        "nodetype" : "namednumber",
                        "number" : "3"
                    },
                },
            },
            "access" : "readwrite",
            "description" :
                """This object indicates the trap and log action. The value
'other' means that the port does not support DDM.""",
        }, # column
        "swDdmPortMgmtTable" : {
            "nodetype" : "table",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.3.2.2",
            "status" : "current",
            "description" :
                """This table contains the configuration of the DDM state and shutdown mode
when any parameter exceeds its threshold.""",
        }, # table
        "swDdmPortMgmtEntry" : {
            "nodetype" : "row",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.3.2.2.1",
            "status" : "current",
            "linkage" : [
                "swDdmPort",
            ],
            "description" :
                """This is an entry of the swDdmPortMgmtTable.""",
        }, # row
        "swDdmPortState" : {
            "nodetype" : "column",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.3.2.2.1.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "enabled" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "disabled" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                },
            },
            "access" : "readwrite",
            "description" :
                """This object indicates the DDM state information by port.""",
        }, # column
        "swDdmPortShutdown" : {
            "nodetype" : "column",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.3.2.2.1.2",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "alarm" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "warning" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                    "none" : {
                        "nodetype" : "namednumber",
                        "number" : "3"
                    },
                    "other" : {
                        "nodetype" : "namednumber",
                        "number" : "4"
                    },
                },
            },
            "access" : "readwrite",
            "description" :
                """This object indicates whether or not to shutdown the port
on which the operating parameter exceeds the specified threshold.""",
        }, # column
        "swDdmNotify" : {
            "nodetype" : "node",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.4",
        }, # node
        "swDdmNotifyPrefix" : {
            "nodetype" : "node",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.4.0",
        }, # node
        "swDdmNotificationBinding" : {
            "nodetype" : "node",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.4.1",
        }, # node
        "swDdmThresholdExceedType" : {
            "nodetype" : "scalar",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.4.1.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "high" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "low" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                },
            },
            "access" : "notifyonly",
            "description" :
                """This object is used by swDdmAlarmTrap and swDdmWarningTrap to indicate if 
the threshold that was exceeded was a high threshold or a low threshold.""",
        }, # scalar
        "swDdmThresholdExceedOrRecover" : {
            "nodetype" : "scalar",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.4.1.2",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "exceed" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "recover" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                },
            },
            "access" : "notifyonly",
            "description" :
                """This object is used by swDdmAlarmTrap and swDdmWarningTrap,to indicate the GBIC
is exceeding its ddm threshold or recover to normal status.""",
        }, # scalar
    }, # nodes

    "notifications" : {
        "swDdmAlarmTrap" : {
            "nodetype" : "notification",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.4.0.1",
            "status" : "current",
            "objects" : {
                "swDdmPort" : {
                    "nodetype" : "object",
                    "module" : "DDM-MGMT-MIB"
                },
                "swDdmThresholdType" : {
                    "nodetype" : "object",
                    "module" : "DDM-MGMT-MIB"
                },
                "swDdmThresholdExceedType" : {
                    "nodetype" : "object",
                    "module" : "DDM-MGMT-MIB"
                },
                "swDdmThresholdExceedOrRecover" : {
                    "nodetype" : "object",
                    "module" : "DDM-MGMT-MIB"
                },
            },
            "description" :
                """The trap is sent when any parameter value exceeds the alarm threshold value
or recover to normal status depending on the configuration of the trap action.""",
        }, # notification
        "swDdmWarningTrap" : {
            "nodetype" : "notification",
            "moduleName" : "DDM-MGMT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.72.4.0.2",
            "status" : "current",
            "objects" : {
                "swDdmPort" : {
                    "nodetype" : "object",
                    "module" : "DDM-MGMT-MIB"
                },
                "swDdmThresholdType" : {
                    "nodetype" : "object",
                    "module" : "DDM-MGMT-MIB"
                },
                "swDdmThresholdExceedType" : {
                    "nodetype" : "object",
                    "module" : "DDM-MGMT-MIB"
                },
                "swDdmThresholdExceedOrRecover" : {
                    "nodetype" : "object",
                    "module" : "DDM-MGMT-MIB"
                },
            },
            "description" :
                """The trap is sent when any parameter value exceeds the warning threshold value
or recover to normal status depending on the configuration of the trap action.""",
        }, # notification
    }, # notifications

}
