# python version 1.0						DO NOT EDIT
#
# Generated by smidump version 0.4.8:
#
#   smidump -f python EQUIPMENT-MIB

FILENAME = "Equipment.mib"

MIB = {
    "moduleName" : "EQUIPMENT-MIB",

    "EQUIPMENT-MIB" : {
        "nodetype" : "module",
        "language" : "SMIv2",
        "organization" :    
            """D-Link Corp.""",
        "contact" : 
            """http://support.dlink.com""",
        "description" :
            """ equipments MIB.""",
        "revisions" : (
            {
                "date" : "2011-04-20 00:00",
                "description" :
                    """[Revision added by libsmi due to a LAST-UPDATED clause.]""",
            },
        ),
        "identity node" : "swEquipmentMIB",
    },

    "imports" : (
        {"module" : "SNMPv2-SMI", "name" : "MODULE-IDENTITY"},
        {"module" : "SNMPv2-SMI", "name" : "OBJECT-TYPE"},
        {"module" : "SNMPv2-TC", "name" : "DateAndTime"},
        {"module" : "SNMPv2-TC", "name" : "TruthValue"},
        {"module" : "SNMPv2-TC", "name" : "DisplayString"},
        {"module" : "SNMPv2-TC", "name" : "RowStatus"},
        {"module" : "Q-BRIDGE-MIB", "name" : "PortList"},
        {"module" : "TIMERANGE-MIB", "name" : "swTimeRangeMgmtRangeName"},
        {"module" : "DLINK-ID-REC-MIB", "name" : "AgentNotifyLevel"},
        {"module" : "DLINK-ID-REC-MIB", "name" : "dlink-common-mgmt"},
    ),

    "typedefs" : {
        "MacAddress" : {
            "basetype" : "OctetString",
            "ranges" : [
            {
                "min" : "6",
                "max" : "6"
            },
            ],
            "range" : {
                "min" : "6",
                "max" : "6"
            },
        },
    }, # typedefs

    "nodes" : {
        "swEquipmentMIB" : {
            "nodetype" : "node",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11",
            "status" : "current",
        }, # node
        "swEquipment" : {
            "nodetype" : "node",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1",
        }, # node
        "swEquipmentCapacity" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Bits",
                    "fanCapable" : {
                        "nodetype" : "namednumber",
                        "number" : "0"
                    },
                    "redundantPowerCapable" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "tempteratureDetection" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                    "stackingCapable" : {
                        "nodetype" : "namednumber",
                        "number" : "3"
                    },
                    "chassisCapable" : {
                        "nodetype" : "namednumber",
                        "number" : "4"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Indicates the equipment capability supported in the system.""",
        }, # scalar
        "swFanTrapState" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.4",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "enabled" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "disabled" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                },
            },
            "access" : "readwrite",
            "description" :
                """Indicate the fan warning event trap state.""",
        }, # scalar
        "swPowerTrapState" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.5",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "enabled" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "disabled" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                },
            },
            "access" : "readwrite",
            "description" :
                """Indicate the power warning event trap state.""",
        }, # scalar
        "swPowerTable" : {
            "nodetype" : "table",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.6",
            "status" : "current",
            "description" :
                """A list of power information values.""",
        }, # table
        "swPowerEntry" : {
            "nodetype" : "row",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.6.1",
            "status" : "current",
            "linkage" : [
                "swPowerUnitIndex",
                "swPowerID",
            ],
            "description" :
                """An entry of power information values.""",
        }, # row
        "swPowerUnitIndex" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.6.1.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "65535"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "65535"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Indicates the unit ID in the System.""",
        }, # column
        "swPowerID" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.6.1.2",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "65535"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "65535"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Indicates ID of the power
1 : main power
2 : redundant power .""",
        }, # column
        "swPowerStatus" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.6.1.3",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "other" : {
                        "nodetype" : "namednumber",
                        "number" : "0"
                    },
                    "lowVoltage" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "overCurrent" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                    "working" : {
                        "nodetype" : "namednumber",
                        "number" : "3"
                    },
                    "fail" : {
                        "nodetype" : "namednumber",
                        "number" : "4"
                    },
                    "connect" : {
                        "nodetype" : "namednumber",
                        "number" : "5"
                    },
                    "disconnect" : {
                        "nodetype" : "namednumber",
                        "number" : "6"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Indicates the current power status.
lowVoltage : The voltage of the power unit is too low.
overCurrent: The current of the power unit is too high.
working    : The power unit is working normally.
fail       : The power unit has failed.
connect    : The power unit is connected but not powered on.
disconnect : The power unit is not connected.""",
        }, # column
        "swFanTable" : {
            "nodetype" : "table",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.7",
            "status" : "current",
            "description" :
                """A list of fan information values.""",
        }, # table
        "swFanEntry" : {
            "nodetype" : "row",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.7.1",
            "status" : "current",
            "linkage" : [
                "swFanUnitIndex",
                "swFanID",
            ],
            "description" :
                """An entry of fan information values.""",
        }, # row
        "swFanUnitIndex" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.7.1.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "65535"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "65535"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Indicates the unit ID in the System.""",
        }, # column
        "swFanID" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.7.1.2",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "65535"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "65535"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Indicates the unit ID.""",
        }, # column
        "swFanStatus" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.7.1.3",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "other" : {
                        "nodetype" : "namednumber",
                        "number" : "0"
                    },
                    "working" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "fail" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                    "speed-0" : {
                        "nodetype" : "namednumber",
                        "number" : "3"
                    },
                    "speed-low" : {
                        "nodetype" : "namednumber",
                        "number" : "4"
                    },
                    "speed-middle" : {
                        "nodetype" : "namednumber",
                        "number" : "5"
                    },
                    "speed-high" : {
                        "nodetype" : "namednumber",
                        "number" : "6"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Indicates the current fan status.
speed-0     : If the fan function is normal and the fan does not spin 
                   due to the temperature not  reaching the threshold,
              the status of the fan is speed 0.
speed-low   : Fan spin using the lowest speed.	
speed-middle: Fan spin using the middle speed.	     		   
speed-high  : Fan spin using the highest speed.""",
        }, # column
        "swFanPostion" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.7.1.4",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "other" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "left" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                    "right" : {
                        "nodetype" : "namednumber",
                        "number" : "3"
                    },
                    "back" : {
                        "nodetype" : "namednumber",
                        "number" : "4"
                    },
                    "cpu" : {
                        "nodetype" : "namednumber",
                        "number" : "5"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Indicates the position of the fan.""",
        }, # column
        "swFanNumber" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.7.1.5",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "65535"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "65535"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Indicates the fan number.""",
        }, # column
        "swFanSpeed" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.7.1.6",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "65535"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "65535"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Indicates the fan work speed(RPM).""",
        }, # column
        "swTemperatureTable" : {
            "nodetype" : "table",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.8",
            "status" : "current",
            "description" :
                """A list of temperature values.""",
        }, # table
        "swTemperatureEntry" : {
            "nodetype" : "row",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.8.1",
            "status" : "current",
            "linkage" : [
                "swTemperatureUnitIndex",
            ],
            "description" :
                """An entry of temperature values.""",
        }, # row
        "swTemperatureUnitIndex" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.8.1.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "65535"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "65535"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Indicates the unit ID in the System.""",
        }, # column
        "swTemperatureCurrent" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.8.1.2",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "-500",
                        "max" : "500"
                    },
                    ],
                    "range" : {
                        "min" : "-500",
                        "max" : "500"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """The shelf current temperature.""",
        }, # column
        "swTemperatureHighThresh" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.8.1.3",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "-500",
                        "max" : "500"
                    },
                    ],
                    "range" : {
                        "min" : "-500",
                        "max" : "500"
                    },
                },
            },
            "access" : "readwrite",
            "description" :
                """The high threshold of shelf temperature.""",
        }, # column
        "swTemperatureLowThresh" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.8.1.4",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "-500",
                        "max" : "500"
                    },
                    ],
                    "range" : {
                        "min" : "-500",
                        "max" : "500"
                    },
                },
            },
            "access" : "readwrite",
            "description" :
                """The low threshold of shelf temperature.""",
        }, # column
        "swUnitMgmt" : {
            "nodetype" : "node",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.9",
        }, # node
        "swUnitStackingVersion" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.9.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "65535"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "65535"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """This object indicates the version of this stacking system.""",
        }, # scalar
        "swUnitMaxSupportedUnits" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.9.2",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "65535"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "65535"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """The maximum number of units that are supported in the system.""",
        }, # scalar
        "swUnitNumOfUnit" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.9.3",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "65535"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "65535"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """The current number of units.""",
        }, # scalar
        "swUnitMgmtTable" : {
            "nodetype" : "table",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.9.4",
            "status" : "current",
            "description" :
                """This table contains the unit information.""",
        }, # table
        "swUnitMgmtEntry" : {
            "nodetype" : "row",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.9.4.1",
            "status" : "current",
            "linkage" : [
                "swUnitMgmtId",
            ],
            "description" :
                """A list of management information for each unit in the system.""",
        }, # row
        "swUnitMgmtId" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.9.4.1.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "1",
                        "max" : "13"
                    },
                    ],
                    "range" : {
                        "min" : "1",
                        "max" : "13"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """This object indicates the specific entry in the stacking/chassis
table.""",
        }, # column
        "swUnitMgmtMacAddr" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.9.4.1.2",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"EQUIPMENT-MIB", "name" : "MacAddress"},
            },
            "access" : "readonly",
            "description" :
                """The MAC address of this unit.""",
        }, # column
        "swUnitMgmtStartPort" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.9.4.1.3",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "1",
                        "max" : "65535"
                    },
                    ],
                    "range" : {
                        "min" : "1",
                        "max" : "65535"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """This object indicates the starting port of this unit.""",
        }, # column
        "swUnitMgmtPortRange" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.9.4.1.4",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "65535"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "65535"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """This object indicates the total ports of this unit.""",
        }, # column
        "swUnitMgmtFrontPanelLedStatus" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.9.4.1.5",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "255"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "255"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """This object is a set of system LED indicators. The first four
octets are defined as a system LED. The first LED is a power LED.
The second LED in the stacking module is a main LED but in the chassis is
a status LED. The third LED is a console LED. The fourth LED is
an RPS (Redundancy Power Supply) LED. The other octets are the
logical port LED (following dot1dBasePort ordering). Every two
bytes are presented to a port. The first byte is presented as the
link/activity LED. The second byte is presented as the speed LED.

system LED:
01 = fail/error/non existence.
02 = work normal.


link/activity LED :
The most significant bit is used for blinking/solid:
   8 = The LED blinks.

The second most significant bit is used for link status:
	1 = link fail.
	2 = link pass.

speed LED :
	01 = 10Mbps.
	02 = 100Mbps.
	03 = 1000Mbps.

The four remaining bits are currently unused and must be set to 0.

Note:
For the DGS-3700, the first five octets are defined as the system LED.
The first LED is the power LED. The second LED is the console LED.
The third LED is the RPS (Redundancy Power Supply) LED. The fourth
LED is the management port LED. The fifth LED is the fan LED.

For the DGS-3200-10 and DGS-3200-16, the first three octets are defined 
as the system LED. The first LED is the power LED. The second LED is the console LED.
The third LED is the RPS (Redundancy Power Supply) LED.
For the DGS-3200-24, the first three octets are defined as the system LED,
the definition of the first three octets is the same as the DGS-3200-10 and DGS-3200-16,
the fourth LED is the SD card LED. The following description is for the SD card LED:
01 = SD card is not present.
02 = SD card is present.
03 = fails to read/write SD card.
04 = read/write SD card successfully.""",
        }, # column
        "swUnitMgmtCtrlMode" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.9.4.1.6",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "other" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "auto" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                    "stand-alone" : {
                        "nodetype" : "namednumber",
                        "number" : "3"
                    },
                    "main" : {
                        "nodetype" : "namednumber",
                        "number" : "4"
                    },
                    "subordinate" : {
                        "nodetype" : "namednumber",
                        "number" : "5"
                    },
                },
            },
            "access" : "readwrite",
            "description" :
                """This object indicates the stacking mode the user configured for
the unit.  This object can only be configured when the device is
in standalone mode.

other (1) - This object indicates the stacking mode that the user
    has configured for the unit. This object can only be configured
    when the device is in standalone mode.
auto (2) - The system will auto-assign a stacking role to this
    unit to be: standalone(3), main(4), or subordinate(5).
standalone (3) - The unit is forced to be in standalone mode.
main (4) - The unit is forced to be in main mode. If this unit is
    selected to be a main, the unit can modify the configuration of the stacking system.
subordinate (5) - The unit is forced to be in subordinate mode. If this unit is
    selected to be a subordinate, it can only view the configuration of
    the stacking system.""",
        }, # column
        "swUnitMgmtCurrentMode" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.9.4.1.7",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "other" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "auto" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                    "stand-alone" : {
                        "nodetype" : "namednumber",
                        "number" : "3"
                    },
                    "main" : {
                        "nodetype" : "namednumber",
                        "number" : "4"
                    },
                    "subordinate" : {
                        "nodetype" : "namednumber",
                        "number" : "5"
                    },
                    "backup-main" : {
                        "nodetype" : "namednumber",
                        "number" : "6"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """The current stacking role of this unit.""",
        }, # column
        "swUnitMgmtVersion" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.9.4.1.8",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "SNMPv2-TC",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "32"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "32"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """This object indicates the version of this stacking unit.""",
        }, # column
        "swUnitMgmtModuleName" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.9.4.1.9",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "SNMPv2-TC",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "32"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "32"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """A textual string containing the stacking unit module name. """,
        }, # column
        "swUnitMgmtPromVersion" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.9.4.1.10",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "SNMPv2-TC",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "255"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "255"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """A textual string containing the PROM version of the
stacking unit. """,
        }, # column
        "swUnitMgmtFirmwareVersion" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.9.4.1.11",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "SNMPv2-TC",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "255"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "255"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """A textual string containing the firmware version of the
stacking unit. """,
        }, # column
        "swUnitMgmtHardwareVersion" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.9.4.1.12",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "SNMPv2-TC",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "255"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "255"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """A textual string containing the hardware version of the
stacking unit. """,
        }, # column
        "swUnitMgmtPriority" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.9.4.1.13",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "1",
                        "max" : "63"
                    },
                    ],
                    "range" : {
                        "min" : "1",
                        "max" : "63"
                    },
                },
            },
            "access" : "readwrite",
            "description" :
                """The Priority of the  stacking unit. """,
        }, # column
        "swUnitMgmtUserSetState" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.9.4.1.14",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "other" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "auto" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                    "user" : {
                        "nodetype" : "namednumber",
                        "number" : "3"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """This object indicates the user set state of this unit.""",
        }, # column
        "swUnitMgmtExistState" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.9.4.1.15",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "exist" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "no-exist" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """The state of existence of this unit.""",
        }, # column
        "swUnitMgmtBoxId" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.9.4.1.16",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "box-1" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "box-2" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                    "box-3" : {
                        "nodetype" : "namednumber",
                        "number" : "3"
                    },
                    "box-4" : {
                        "nodetype" : "namednumber",
                        "number" : "4"
                    },
                    "box-5" : {
                        "nodetype" : "namednumber",
                        "number" : "5"
                    },
                    "box-6" : {
                        "nodetype" : "namednumber",
                        "number" : "6"
                    },
                    "box-7" : {
                        "nodetype" : "namednumber",
                        "number" : "7"
                    },
                    "box-8" : {
                        "nodetype" : "namednumber",
                        "number" : "8"
                    },
                    "box-9" : {
                        "nodetype" : "namednumber",
                        "number" : "9"
                    },
                    "box-10" : {
                        "nodetype" : "namednumber",
                        "number" : "10"
                    },
                    "box-11" : {
                        "nodetype" : "namednumber",
                        "number" : "11"
                    },
                    "box-12" : {
                        "nodetype" : "namednumber",
                        "number" : "12"
                    },
                    "auto" : {
                        "nodetype" : "namednumber",
                        "number" : "13"
                    },
                },
            },
            "access" : "readwrite",
            "description" :
                """The box ID of the stacking unit.
When show, it shows the current box ID of this unit;
When set, it sets the new box ID, and the new box ID will
take effect after the next boot.""",
        }, # column
        "swUnitMgmtSerialNumber" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.9.4.1.17",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """A text string containing the serial number of the stacking unit.""",
        }, # column
        "swUnitTopology" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.9.5",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "stand-alone" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "duplex-chain" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                    "duplex-ring" : {
                        "nodetype" : "namednumber",
                        "number" : "3"
                    },
                    "star" : {
                        "nodetype" : "namednumber",
                        "number" : "4"
                    },
                    "unstable" : {
                        "nodetype" : "namednumber",
                        "number" : "5"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """The stacking topology state.""",
        }, # scalar
        "swUnitStackMode" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.9.6",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "enabled" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "disabled" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                },
            },
            "access" : "readwrite",
            "description" :
                """Indicates the stacking mode supported in the system.""",
        }, # scalar
        "swUnitStackForceMainRole" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.9.7",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "enabled" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "disabled" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                },
            },
            "access" : "readwrite",
            "description" :
                """Indicates the stack force main role mode supported in the system.""",
        }, # scalar
        "swUnitStackTrapState" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.9.8",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "enabled" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "disabled" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                },
            },
            "access" : "readwrite",
            "default" : "enabled",
            "description" :
                """Indicates the stacking trap state.""",
        }, # scalar
        "swUnitStackLogState" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.9.9",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "enabled" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "disabled" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                },
            },
            "access" : "readwrite",
            "default" : "enabled",
            "description" :
                """Indicates the stacking log state.""",
        }, # scalar
        "swExternalAlarmTable" : {
            "nodetype" : "table",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.10",
            "status" : "current",
            "description" :
                """A list of the status of each of the alarm channels by this agent.""",
        }, # table
        "swExternalAlarmEntry" : {
            "nodetype" : "row",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.10.1",
            "status" : "current",
            "linkage" : [
                "swExternalAlarmChannel",
            ],
            "description" :
                """An entry containing objects with the status of each alarm channel.""",
        }, # row
        "swExternalAlarmChannel" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.10.1.1",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Integer32"},
            },
            "access" : "readonly",
            "description" :
                """The number of the alarm channel.""",
        }, # column
        "swExternalAlarmMessage" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.10.1.2",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "SNMPv2-TC",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "128"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "128"
                    },
                },
            },
            "access" : "readwrite",
            "description" :
                """Used to configure the alarm message when an alarm occurs on this channel.
If no alarm message is configured on this channel, a default alarm message will be generated.""",
        }, # column
        "swExternalAlarmStatus" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.10.1.3",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "alarming" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "normal" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Shows the current status of each alarm channel.""",
        }, # column
        "swEquipmentPowerSaving" : {
            "nodetype" : "node",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.11",
        }, # node
        "swEquipPowerSavingLinkDetectState" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.11.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "enabled" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "disabled" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                },
            },
            "access" : "readwrite",
            "description" :
                """Indicates the equipment reduced power consumption state.""",
        }, # scalar
        "swEquipPowerSavingLenDetect" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.11.2",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "enabled" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "disabled" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                },
            },
            "access" : "readwrite",
            "description" :
                """Indicates the equipment reduced power consumption state with a link partner.""",
        }, # scalar
        "swEquipPowerSavingHiberState" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.11.3",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "enabled" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "disabled" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                },
            },
            "access" : "readwrite",
            "default" : "disabled",
            "description" :
                """This object indicates the power saving state of system hibernation.""",
        }, # scalar
        "swEquipPowerSavingPortLEDState" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.11.4",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "enabled" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "disabled" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                },
            },
            "access" : "readwrite",
            "default" : "disabled",
            "description" :
                """This object indicates the power saving state of port LED.""",
        }, # scalar
        "swEquipPowerSavingPortState" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.11.5",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "enabled" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "disabled" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                },
            },
            "access" : "readwrite",
            "default" : "disabled",
            "description" :
                """This object indicates the power saving state of port.""",
        }, # scalar
        "swEquipPowerSavingScheduleCtrl" : {
            "nodetype" : "node",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.11.6",
        }, # node
        "swEquipPowerSavingHibernationTable" : {
            "nodetype" : "table",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.11.6.1",
            "status" : "current",
            "description" :
                """A list of the system hibernation configurations of the power saving.""",
        }, # table
        "swEquipPowerSavingHibernationEntry" : {
            "nodetype" : "row",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.11.6.1.1",
            "create" : "true",
            "status" : "current",
            "linkage" : [
                "swTimeRangeMgmtRangeName",
            ],
            "description" :
                """An entry containing the system hibernation configurations of the power saving.""",
        }, # row
        "swEquipPowerSavingHiberRowStatus" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.11.6.1.1.100",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "RowStatus"},
            },
            "access" : "readwrite",
            "description" :
                """This object indicates the status of this entry.""",
        }, # column
        "swEquipPowerSavingPortLedTable" : {
            "nodetype" : "table",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.11.6.2",
            "status" : "current",
            "description" :
                """A list of the port LED configurations of the power saving.""",
        }, # table
        "swEquipPowerSavingPortLedEntry" : {
            "nodetype" : "row",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.11.6.2.1",
            "create" : "true",
            "status" : "current",
            "linkage" : [
                "swTimeRangeMgmtRangeName",
            ],
            "description" :
                """An entry containing the port LED configurations of the power saving.""",
        }, # row
        "swEquipPowerSavingPortLedRowStatus" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.11.6.2.1.100",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "RowStatus"},
            },
            "access" : "readwrite",
            "description" :
                """This object indicates the status of this entry.""",
        }, # column
        "swEquipPowerSavingPortTable" : {
            "nodetype" : "table",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.11.6.3",
            "status" : "current",
            "description" :
                """A list of the port configurations of the power saving.""",
        }, # table
        "swEquipPowerSavingPortEntry" : {
            "nodetype" : "row",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.11.6.3.1",
            "create" : "true",
            "status" : "current",
            "linkage" : [
                "swEquipPowerSavingPortIndex",
                "swTimeRangeMgmtRangeName",
            ],
            "description" :
                """An entry containing the port configurations of the power saving.""",
        }, # row
        "swEquipPowerSavingPortIndex" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.11.6.3.1.1",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Integer32"},
            },
            "access" : "noaccess",
            "description" :
                """Indicates the module's port number.(1..Max port number in
the module).""",
        }, # column
        "swEquipPowerSavingPortRowStatus" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.11.6.3.1.100",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "RowStatus"},
            },
            "access" : "readwrite",
            "description" :
                """This object indicates the status of this entry.""",
        }, # column
        "swEquipEeeMgmt" : {
            "nodetype" : "node",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.11.20",
        }, # node
        "swEquipEeeState" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.11.20.1",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"Q-BRIDGE-MIB", "name" : "PortList"},
            },
            "access" : "readwrite",
            "description" :
                """This object indicates the EEE state of all ports.

Note:
If the port's bit has a value of '1', specifies the EEE (Energy Efficient Ethernet) 
state of this port is 'Enabled',
otherwise, if the port's bit has a value of '0', specifies the EEE 
state of this port is 'Disabled'.""",
        }, # scalar
        "swEquipmentTemperatureCtrl" : {
            "nodetype" : "node",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.12",
        }, # node
        "swTemperatureTrapState" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.12.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "enabled" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "disabled" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                },
            },
            "access" : "readwrite",
            "description" :
                """This object can enable or disable the warning temperature trap.""",
        }, # scalar
        "swTemperatureLogState" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.12.2",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "enabled" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "disabled" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                },
            },
            "access" : "readwrite",
            "description" :
                """This object can enable or disable the warning temperature log.""",
        }, # scalar
        "swEquipmentLEDCtrl" : {
            "nodetype" : "node",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.13",
        }, # node
        "swEquipmentPortLEDState" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.13.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "enabled" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "disabled" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                },
            },
            "access" : "readwrite",
            "default" : "enabled",
            "description" :
                """This object indicates the LED admin state of all ports.""",
        }, # scalar
        "swExternalAlarmStackingTable" : {
            "nodetype" : "table",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.15",
            "status" : "current",
            "description" :
                """A list of the status of each of the alarm channels by this agent.""",
        }, # table
        "swExternalAlarmStackingEntry" : {
            "nodetype" : "row",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.15.1",
            "status" : "current",
            "linkage" : [
                "swExternalAlarmStackingUnitIndex",
                "swExternalAlarmStackingChannel",
            ],
            "description" :
                """An entry containing objects with the status of each alarm channel.""",
        }, # row
        "swExternalAlarmStackingUnitIndex" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.15.1.1",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Integer32"},
            },
            "access" : "noaccess",
            "description" :
                """Indicates the unit ID in the System..""",
        }, # column
        "swExternalAlarmStackingChannel" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.15.1.2",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Integer32"},
            },
            "access" : "noaccess",
            "description" :
                """The number of the alarm channel.""",
        }, # column
        "swExternalAlarmStackingMessage" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.15.1.3",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "SNMPv2-TC",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "128"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "128"
                    },
                },
            },
            "access" : "readwrite",
            "description" :
                """Used to configure the alarm message when an alarm occurs on this channel.
If no alarm message is configured on this channel, a default alarm message will be generated.""",
        }, # column
        "swExternalAlarmStackingStatus" : {
            "nodetype" : "column",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.1.15.1.4",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "alarming" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "normal" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Shows the current status of each alarm channel.""",
        }, # column
        "swEquipmentNotify" : {
            "nodetype" : "node",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2",
        }, # node
        "swEquipmentNotifyMgmt" : {
            "nodetype" : "node",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.1",
        }, # node
        "swEquipUnitNotifyMgmt" : {
            "nodetype" : "node",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.1.1",
        }, # node
        "swUnitInsertSeverity" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.1.1.1",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"DLINK-ID-REC-MIB", "name" : "AgentNotifyLevel"},
            },
            "access" : "readwrite",
            "description" :
                """Indicates the swUnitInsert detection level.""",
        }, # scalar
        "swUnitRemoveSeverity" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.1.1.2",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"DLINK-ID-REC-MIB", "name" : "AgentNotifyLevel"},
            },
            "access" : "readwrite",
            "description" :
                """Indicates the swUnitRemove detection level.""",
        }, # scalar
        "swUnitFailureSeverity" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.1.1.3",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"DLINK-ID-REC-MIB", "name" : "AgentNotifyLevel"},
            },
            "access" : "readwrite",
            "description" :
                """Indicates the swUnitFailure detection level.""",
        }, # scalar
        "swEquipPowerNotifyMgmt" : {
            "nodetype" : "node",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.1.2",
        }, # node
        "swPowerStatusChgSeverity" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.1.2.1",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"DLINK-ID-REC-MIB", "name" : "AgentNotifyLevel"},
            },
            "access" : "readwrite",
            "description" :
                """Indicates the swPowerStatusChg detection level.""",
        }, # scalar
        "swPowerFailureSeverity" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.1.2.2",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"DLINK-ID-REC-MIB", "name" : "AgentNotifyLevel"},
            },
            "access" : "readwrite",
            "description" :
                """Indicates the swPowerFailure detection level.""",
        }, # scalar
        "swPowerRecoverSeverity" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.1.2.3",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"DLINK-ID-REC-MIB", "name" : "AgentNotifyLevel"},
            },
            "access" : "readwrite",
            "description" :
                """Indicates the swPowerRecover detection level.""",
        }, # scalar
        "swEquipFanNotifyMgmt" : {
            "nodetype" : "node",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.1.3",
        }, # node
        "swFanFailureSeverity" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.1.3.1",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"DLINK-ID-REC-MIB", "name" : "AgentNotifyLevel"},
            },
            "access" : "readwrite",
            "description" :
                """Indicates the swFanFailure detection level.""",
        }, # scalar
        "swFanRecoverSeverity" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.1.3.2",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"DLINK-ID-REC-MIB", "name" : "AgentNotifyLevel"},
            },
            "access" : "readwrite",
            "description" :
                """Indicates the swFanRecover detection level.""",
        }, # scalar
        "swEquipTemperatureNotifyMgmt" : {
            "nodetype" : "node",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.1.4",
        }, # node
        "swHighTemperatureSeverity" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.1.4.1",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"DLINK-ID-REC-MIB", "name" : "AgentNotifyLevel"},
            },
            "access" : "readwrite",
            "description" :
                """Indicates the swHighTemperature detection level.""",
        }, # scalar
        "swHighTemperatureRecoverSeverity" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.1.4.2",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"DLINK-ID-REC-MIB", "name" : "AgentNotifyLevel"},
            },
            "access" : "readwrite",
            "description" :
                """Indicates the swHighTemperatureRecover detection level.""",
        }, # scalar
        "swLowTemperatureSeverity" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.1.4.3",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"DLINK-ID-REC-MIB", "name" : "AgentNotifyLevel"},
            },
            "access" : "readwrite",
            "description" :
                """Indicates the swLowTemperature detection level.""",
        }, # scalar
        "swLowTemperatureRecoverSeverity" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.1.4.4",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"DLINK-ID-REC-MIB", "name" : "AgentNotifyLevel"},
            },
            "access" : "readwrite",
            "description" :
                """Indicates the swLowTemperatureRecover detection level.""",
        }, # scalar
        "swEquipmentNotification" : {
            "nodetype" : "node",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.2",
        }, # node
        "swEquipUnitNotification" : {
            "nodetype" : "node",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.2.1",
        }, # node
        "swEquipUnitNotifyPrefix" : {
            "nodetype" : "node",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.2.1.0",
        }, # node
        "swEquipPowerNotification" : {
            "nodetype" : "node",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.2.2",
        }, # node
        "swEquipPowerNotifyPerfix" : {
            "nodetype" : "node",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.2.2.0",
        }, # node
        "swEquipFanNotification" : {
            "nodetype" : "node",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.2.3",
        }, # node
        "swEquipFanNotifyPrefix" : {
            "nodetype" : "node",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.2.3.0",
        }, # node
        "swEquipTemperatureNotification" : {
            "nodetype" : "node",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.2.4",
        }, # node
        "swEquipTemperatureNotifyPrefix" : {
            "nodetype" : "node",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.2.4.0",
        }, # node
        "swEquipExternalAlarmNotification" : {
            "nodetype" : "node",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.2.5",
        }, # node
        "swEquipExternalAlarmNotifyPrefix" : {
            "nodetype" : "node",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.2.5.0",
        }, # node
        "swNotificationBindings" : {
            "nodetype" : "node",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.3",
        }, # node
        "swEquipTemperNotifyBindings" : {
            "nodetype" : "node",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.3.1",
        }, # node
        "swTemperSensorID" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.3.1.1",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Integer32"},
            },
            "access" : "notifyonly",
            "description" :
                """This object indicates the ID of the temperature sensor in the unit.""",
        }, # scalar
        "swEquipUnitNotifyBindings" : {
            "nodetype" : "node",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.3.2",
        }, # node
        "swStackTopologyType" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.3.2.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "chain" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "ring" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                },
            },
            "access" : "notifyonly",
            "description" :
                """This object indicates the MAC address of the switch.""",
        }, # scalar
        "swStackRoleChangeType" : {
            "nodetype" : "scalar",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.3.2.2",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "backup-to-main" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "subordinate-to-main" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                },
            },
            "access" : "notifyonly",
            "description" :
                """This object indicates the role information of the switch.""",
        }, # scalar
    }, # nodes

    "notifications" : {
        "swUnitInsert" : {
            "nodetype" : "notification",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.2.1.0.1",
            "status" : "current",
            "objects" : {
                "swUnitMgmtId" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
                "swUnitMgmtMacAddr" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
            },
            "description" :
                """Unit Hot Insert notification.""",
        }, # notification
        "swUnitRemove" : {
            "nodetype" : "notification",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.2.1.0.2",
            "status" : "current",
            "objects" : {
                "swUnitMgmtId" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
                "swUnitMgmtMacAddr" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
            },
            "description" :
                """Unit Hot Remove notification.""",
        }, # notification
        "swUnitFailure" : {
            "nodetype" : "notification",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.2.1.0.3",
            "status" : "current",
            "objects" : {
                "swUnitMgmtId" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
            },
            "description" :
                """Unit Failure notification.""",
        }, # notification
        "swUnitTPChange" : {
            "nodetype" : "notification",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.2.1.0.4",
            "status" : "current",
            "objects" : {
                "swStackTopologyType" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
                "swUnitMgmtId" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
                "swUnitMgmtMacAddr" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
            },
            "description" :
                """The stacking topology change notification.""",
        }, # notification
        "swUnitRoleChange" : {
            "nodetype" : "notification",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.2.1.0.5",
            "status" : "current",
            "objects" : {
                "swStackRoleChangeType" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
                "swUnitMgmtId" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
            },
            "description" :
                """The stacking unit role change notification.""",
        }, # notification
        "swPowerStatusChg" : {
            "nodetype" : "notification",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.2.2.0.1",
            "status" : "current",
            "objects" : {
                "swPowerUnitIndex" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
                "swPowerID" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
                "swPowerStatus" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
            },
            "description" :
                """Power Status change notification. The notification is issued 
when the swPowerStatus changes in the following cases:
lowVoltage  -> overCurrent. 
lowVoltage  -> working. 
lowVoltage  -> disconnect. 
lowVoltage  -> connect. 
overCurrent -> lowVoltage. 
overCurrent -> working. 
overCurrent -> disconnect. 
overCurrent -> connect. 
working     -> lowVoltage. 
working     -> overCurrent. 
working     -> connect. 
working     -> disconnect. 
fail        -> connect. 
fail        -> disconnect. 
connect     -> lowVoltage. 
connect     -> overCurrent. 
connect     -> working. 
connect     -> disconnect. 
disconnect  -> lowVoltage. 
disconnect  -> overCurrent. 
disconnect  -> working. 
disconnect  -> connect.""",
        }, # notification
        "swPowerFailure" : {
            "nodetype" : "notification",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.2.2.0.2",
            "status" : "current",
            "objects" : {
                "swPowerUnitIndex" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
                "swPowerID" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
                "swPowerStatus" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
            },
            "description" :
                """Power Failure notification. The notification is issued 
when the swPowerStatus changes in the following cases:
lowVoltage  -> fail. 
			 overCurrent -> fail. 
working     -> fail. 
connect     -> fail. 
disconnect  -> fail.""",
        }, # notification
        "swPowerRecover" : {
            "nodetype" : "notification",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.2.2.0.3",
            "status" : "current",
            "objects" : {
                "swPowerUnitIndex" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
                "swPowerID" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
                "swPowerStatus" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
            },
            "description" :
                """Power Recover notification. The notification is issued
when the swPowerStatus changes in the following cases:
fail -> lowVoltage.  
fail -> overCurrent. 
fail -> working.""",
        }, # notification
        "swFanFailure" : {
            "nodetype" : "notification",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.2.3.0.1",
            "status" : "current",
            "objects" : {
                "swFanUnitIndex" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
                "swFanID" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
            },
            "description" :
                """Fan Failure notification.""",
        }, # notification
        "swFanRecover" : {
            "nodetype" : "notification",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.2.3.0.2",
            "status" : "current",
            "objects" : {
                "swFanUnitIndex" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
                "swFanID" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
            },
            "description" :
                """Fan Recover notification.""",
        }, # notification
        "swHighTemperature" : {
            "nodetype" : "notification",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.2.4.0.1",
            "status" : "current",
            "objects" : {
                "swTemperatureUnitIndex" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
                "swTemperSensorID" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
                "swTemperatureCurrent" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
            },
            "description" :
                """High Temperature notification.""",
        }, # notification
        "swHighTemperatureRecover" : {
            "nodetype" : "notification",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.2.4.0.2",
            "status" : "current",
            "objects" : {
                "swTemperatureUnitIndex" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
                "swTemperSensorID" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
                "swTemperatureCurrent" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
            },
            "description" :
                """High Temperature notification.""",
        }, # notification
        "swLowTemperature" : {
            "nodetype" : "notification",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.2.4.0.3",
            "status" : "current",
            "objects" : {
                "swTemperatureUnitIndex" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
                "swTemperSensorID" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
                "swTemperatureCurrent" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
            },
            "description" :
                """Low Temperature notification.""",
        }, # notification
        "swLowTemperatureRecover" : {
            "nodetype" : "notification",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.2.4.0.4",
            "status" : "current",
            "objects" : {
                "swTemperatureUnitIndex" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
                "swTemperSensorID" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
                "swTemperatureCurrent" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
            },
            "description" :
                """Low Temperature notification.""",
        }, # notification
        "swExternalAlarm" : {
            "nodetype" : "notification",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.2.5.0.1",
            "status" : "current",
            "objects" : {
                "swExternalAlarmChannel" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
                "swExternalAlarmMessage" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
            },
            "description" :
                """The notice of an Alarm in the specified channel.""",
        }, # notification
        "swExternalAlarmStacking" : {
            "nodetype" : "notification",
            "moduleName" : "EQUIPMENT-MIB",
            "oid" : "1.3.6.1.4.1.171.12.11.2.2.5.0.2",
            "status" : "current",
            "objects" : {
                "swExternalAlarmStackingUnitIndex" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
                "swExternalAlarmStackingChannel" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
                "swExternalAlarmStackingMessage" : {
                    "nodetype" : "object",
                    "module" : "EQUIPMENT-MIB"
                },
            },
            "description" :
                """The notice of an Alarm in the specified channel.""",
        }, # notification
    }, # notifications

}
