# python version 1.0						DO NOT EDIT
#
# Generated by smidump version 0.4.8:
#
#   smidump -f python DKSF-60-4-X-X-X

FILENAME = "DKSF_60.4.2_MB.mib"

MIB = {
    "moduleName" : "DKSF-60-4-X-X-X",

    "DKSF-60-4-X-X-X" : {
        "nodetype" : "module",
        "language" : "SMIv2",
        "organization" :    
            """NetPing East, Alentis Electronics""",
        "contact" : 
            """developers@netping.ru""",
        "description" :
            """Generic MIB for NetPing remote sensing and control""",
        "revisions" : (
            {
                "date" : "2014-10-23 00:00",
                "description" :
                    """Major update for DKSF 60.4""",
            },
            {
                "date" : "2012-10-09 00:00",
                "description" :
                    """npTrapEmailTo variable is added in Traps for forwarding to email with external service""",
            },
            {
                "date" : "2012-03-01 00:00",
                "description" :
                    """npReboot branch is added""",
            },
            {
                "date" : "2011-04-11 00:00",
                "description" :
                    """npIoPulseCounter, npIoSinglePulseDuration, npIoSinglePulseStart is added
Identification is changed from DKSF 52.3 to DKSF 52.4""",
            },
            {
                "date" : "2011-02-05 00:00",
                "description" :
                    """npIoCurLoop Traps""",
            },
            {
                "date" : "2011-01-28 00:00",
                "description" :
                    """DKSF 50.9.1.A-2,-3,-10 - IR module (DKST28) support,
new Trap definitions for npIO and npThermo.
It's NO backward compatibility with DKSF 50.8 on Traps!""",
            },
            {
                "date" : "2010-04-14 00:00",
                "description" :
                    """SMIv2-style rewrite""",
            },
        ),
        "identity node" : "netPing",
    },

    "imports" : (
        {"module" : "SNMPv2-SMI", "name" : "enterprises"},
        {"module" : "SNMPv2-SMI", "name" : "MODULE-IDENTITY"},
        {"module" : "SNMPv2-SMI", "name" : "OBJECT-TYPE"},
        {"module" : "SNMPv2-SMI", "name" : "Counter32"},
        {"module" : "SNMPv2-SMI", "name" : "Gauge32"},
        {"module" : "SNMPv2-SMI", "name" : "Counter64"},
        {"module" : "SNMPv2-SMI", "name" : "Integer32"},
        {"module" : "SNMPv2-SMI", "name" : "TimeTicks"},
        {"module" : "SNMPv2-SMI", "name" : "NOTIFICATION-TYPE"},
        {"module" : "SNMPv2-TC", "name" : "TEXTUAL-CONVENTION"},
        {"module" : "SNMPv2-TC", "name" : "DisplayString"},
        {"module" : "SNMPv2-TC", "name" : "TruthValue"},
        {"module" : "SNMPv2-TC", "name" : "TimeStamp"},
        {"module" : "SNMPv2-MIB", "name" : "snmpTraps"},
    ),

    "nodes" : {
        "lightcom" : {
            "nodetype" : "node",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728",
        }, # node
        "netPing" : {
            "nodetype" : "node",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.50",
            "status" : "current",
        }, # node
        "npReboot" : {
            "nodetype" : "node",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.911",
        }, # node
        "npSoftReboot" : {
            "nodetype" : "scalar",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.911.1",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Integer32"},
            },
            "access" : "readwrite",
            "description" :
                """Write 1 to reboot device after 
current operations completition""",
        }, # scalar
        "npResetStack" : {
            "nodetype" : "scalar",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.911.2",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Integer32"},
            },
            "access" : "readwrite",
            "description" :
                """Write 1 to re-initialize network 
stack""",
        }, # scalar
        "npForcedReboot" : {
            "nodetype" : "scalar",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.911.3",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Integer32"},
            },
            "access" : "readwrite",
            "description" :
                """Write 1 to immediate forced reboot""",
        }, # scalar
        "npRelay" : {
            "nodetype" : "node",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.5500",
        }, # node
        "npRelayTable" : {
            "nodetype" : "table",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.5500.5",
            "status" : "current",
            "description" :
                """Watchdog and outlet/relay control table""",
        }, # table
        "npRelayEntry" : {
            "nodetype" : "row",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.5500.5.1",
            "status" : "current",
            "linkage" : [
                "npRelayN",
            ],
            "description" :
                """Relay/outlet table row""",
        }, # row
        "npRelayN" : {
            "nodetype" : "column",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.5500.5.1.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "1",
                        "max" : "2"
                    },
                    ],
                    "range" : {
                        "min" : "1",
                        "max" : "2"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """The N of output relay""",
        }, # column
        "npRelayMode" : {
            "nodetype" : "column",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.5500.5.1.2",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "off" : {
                        "nodetype" : "namednumber",
                        "number" : "0"
                    },
                    "on" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "watchdog" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                    "schedule" : {
                        "nodetype" : "namednumber",
                        "number" : "3"
                    },
                    "scheduleAndWatchdog" : {
                        "nodetype" : "namednumber",
                        "number" : "4"
                    },
                    "logic" : {
                        "nodetype" : "namednumber",
                        "number" : "5"
                    },
                },
            },
            "access" : "readwrite",
            "description" :
                """Control of relay:
0 - manual off 
1 - manual on
2 - watchdog
3 - schedule
4 - both schedule and watchdog (while switched on by schedule)
5 - logic""",
        }, # column
        "npRelayStartReset" : {
            "nodetype" : "column",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.5500.5.1.3",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Integer32"},
            },
            "access" : "readwrite",
            "description" :
                """Write 1 to start reset (switch relay off for some time)""",
        }, # column
        "npRelayMemo" : {
            "nodetype" : "column",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.5500.5.1.6",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """Relay memo""",
        }, # column
        "npRelayFlip" : {
            "nodetype" : "column",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.5500.5.1.14",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "flip" : {
                        "nodetype" : "namednumber",
                        "number" : "-1"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Write -1 to flip between manual on and manual off states of relay""",
        }, # column
        "npRelayState" : {
            "nodetype" : "column",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.5500.5.1.15",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "off" : {
                        "nodetype" : "namednumber",
                        "number" : "0"
                    },
                    "on" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Actual relay state at the moment, 
regardless of source of control.
0 - relay is off 
1 - relay is on""",
        }, # column
        "npPwr" : {
            "nodetype" : "node",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.5800",
        }, # node
        "npPwrTable" : {
            "nodetype" : "table",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.5800.3",
            "status" : "current",
            "description" :
                """Watchdog and outlet/relay control table""",
        }, # table
        "npPwrEntry" : {
            "nodetype" : "row",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.5800.3.1",
            "status" : "current",
            "linkage" : [
                "npPwrChannelN",
            ],
            "description" :
                """Watchdog and outlet/relay control table row""",
        }, # row
        "npPwrChannelN" : {
            "nodetype" : "column",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.5800.3.1.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "1",
                        "max" : "2"
                    },
                    ],
                    "range" : {
                        "min" : "1",
                        "max" : "2"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """The id of watchdog/power channel""",
        }, # column
        "npPwrStartReset" : {
            "nodetype" : "column",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.5800.3.1.2",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "2"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "2"
                    },
                },
            },
            "access" : "readwrite",
            "description" :
                """Write 1 to start forced reset
On read:
0 - normal operation
1 - reset is active
2 - reboot pause is active or watchdog is inactive""",
        }, # column
        "npPwrManualMode" : {
            "nodetype" : "column",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.5800.3.1.3",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "off" : {
                        "nodetype" : "namednumber",
                        "number" : "0"
                    },
                    "on" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "watchdog" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                    "schedule" : {
                        "nodetype" : "namednumber",
                        "number" : "3"
                    },
                    "scheduleAndWatchdog" : {
                        "nodetype" : "namednumber",
                        "number" : "4"
                    },
                    "logic" : {
                        "nodetype" : "namednumber",
                        "number" : "5"
                    },
                },
            },
            "access" : "readwrite",
            "description" :
                """Mode of power channel 
0 - manual off 
1 - manual on
2 - watchdog
3 - schedule
4 - schedule and watchdog
5 - controlled by Logic""",
        }, # column
        "npPwrResetsCounter" : {
            "nodetype" : "column",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.5800.3.1.4",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "65535"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "65535"
                    },
                },
            },
            "access" : "readwrite",
            "description" :
                """Counter of watchdog resets
Write 0 to clear.""",
        }, # column
        "npPwrRepeatingResetsCounter" : {
            "nodetype" : "column",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.5800.3.1.5",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "65535"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "65535"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Counter of continous failed 
watchdog resets""",
        }, # column
        "npPwrMemo" : {
            "nodetype" : "column",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.5800.3.1.6",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """Relay channel memo""",
        }, # column
        "npPwrRelayFlip" : {
            "nodetype" : "column",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.5800.3.1.14",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "flip" : {
                        "nodetype" : "namednumber",
                        "number" : "-1"
                    },
                },
            },
            "access" : "readwrite",
            "description" :
                """Write -1 to flip between manual on and manual off states of relay""",
        }, # column
        "npPwrRelayState" : {
            "nodetype" : "column",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.5800.3.1.15",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "off" : {
                        "nodetype" : "namednumber",
                        "number" : "0"
                    },
                    "on" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Actual relay state at the moment, 
regardless of source of control.
0 - relay is off 
1 - relay is on""",
        }, # column
        "npIr" : {
            "nodetype" : "node",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.7900",
        }, # node
        "npIrCtrl" : {
            "nodetype" : "node",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.7900.1",
        }, # node
        "npIrPlayCmd" : {
            "nodetype" : "scalar",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.7900.1.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "1",
                        "max" : "16"
                    },
                    ],
                    "range" : {
                        "min" : "1",
                        "max" : "16"
                    },
                },
            },
            "access" : "readwrite",
            "description" :
                """Write IR command number to send IR command""",
        }, # scalar
        "npIrReset" : {
            "nodetype" : "scalar",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.7900.1.2",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "1"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "1"
                    },
                },
            },
            "access" : "readwrite",
            "description" :
                """Write 1 to reset IR transiever.
After reset, send IR command and check npIrStatus.""",
        }, # scalar
        "npIrStatus" : {
            "nodetype" : "scalar",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.7900.1.3",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "ok" : {
                        "nodetype" : "namednumber",
                        "number" : "0"
                    },
                    "busyCaptureWaitingButton" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "busyCaptureWaitingIr" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                    "busyPlayback" : {
                        "nodetype" : "namednumber",
                        "number" : "3"
                    },
                    "error" : {
                        "nodetype" : "namednumber",
                        "number" : "255"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """IR transiever status""",
        }, # scalar
        "npCurLoop" : {
            "nodetype" : "node",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8300",
        }, # node
        "npCurLoopTable" : {
            "nodetype" : "table",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8300.1",
            "status" : "current",
            "description" :
                """Current loop sensors Table""",
        }, # table
        "npCurLoopEntry" : {
            "nodetype" : "row",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8300.1.1",
            "status" : "current",
            "linkage" : [
                "npCurLoopN",
            ],
            "description" :
                """Current loop sensors Table Row""",
        }, # row
        "npCurLoopN" : {
            "nodetype" : "column",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8300.1.1.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "1",
                        "max" : "8"
                    },
                    ],
                    "range" : {
                        "min" : "1",
                        "max" : "8"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Index of current loop, 1 to max supported""",
        }, # column
        "npCurLoopStatus" : {
            "nodetype" : "column",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8300.1.1.2",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "ok" : {
                        "nodetype" : "namednumber",
                        "number" : "0"
                    },
                    "alert" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "cut" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                    "short" : {
                        "nodetype" : "namednumber",
                        "number" : "3"
                    },
                    "notPowered" : {
                        "nodetype" : "namednumber",
                        "number" : "4"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Status of the loop
0=Normal, 1=Alert, 2=Cut, 3=Short, 4=Not Powered""",
        }, # column
        "npCurLoopI" : {
            "nodetype" : "column",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8300.1.1.3",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "99999"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "99999"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Loop current, mA""",
        }, # column
        "npCurLoopV" : {
            "nodetype" : "column",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8300.1.1.4",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "99999"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "99999"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Voltage drop on the loop, mV""",
        }, # column
        "npCurLoopR" : {
            "nodetype" : "column",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8300.1.1.5",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "99999"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "99999"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Resistance of the loop, Ohm""",
        }, # column
        "npCurLoopPower" : {
            "nodetype" : "column",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8300.1.1.7",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "off" : {
                        "nodetype" : "namednumber",
                        "number" : "0"
                    },
                    "on" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "cyclePower" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                },
            },
            "access" : "readwrite",
            "description" :
                """Control of loop power
0=Off, 1=On, 2=reset by off/on power""",
        }, # column
        "npCurLoopTraps" : {
            "nodetype" : "node",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8300.2",
        }, # node
        "npCurLoopTrapPrefix" : {
            "nodetype" : "node",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8300.2.0",
        }, # node
        "npCurLoopTrapN" : {
            "nodetype" : "scalar",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8300.2.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "1",
                        "max" : "8"
                    },
                    ],
                    "range" : {
                        "min" : "1",
                        "max" : "8"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Index of current loop, which status has changed""",
        }, # scalar
        "npCurLoopTrapStatus" : {
            "nodetype" : "scalar",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8300.2.2",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "ok" : {
                        "nodetype" : "namednumber",
                        "number" : "0"
                    },
                    "alert" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "cut" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                    "short" : {
                        "nodetype" : "namednumber",
                        "number" : "3"
                    },
                    "notPowered" : {
                        "nodetype" : "namednumber",
                        "number" : "4"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Status of the loop
0=Normal, 1=Alert, 2=Cut, 3=Short, 4=Not Powered""",
        }, # scalar
        "npCurLoopTrapI" : {
            "nodetype" : "scalar",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8300.2.3",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "99999"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "99999"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Loop current, mA""",
        }, # scalar
        "npCurLoopTrapV" : {
            "nodetype" : "scalar",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8300.2.4",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "99999"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "99999"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Voltage drop on the loop, mV""",
        }, # scalar
        "npCurLoopTrapR" : {
            "nodetype" : "scalar",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8300.2.5",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "99999"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "99999"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Resistance of the loop, Ohm""",
        }, # scalar
        "npCurLoopTrapPower" : {
            "nodetype" : "scalar",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8300.2.7",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "off" : {
                        "nodetype" : "namednumber",
                        "number" : "0"
                    },
                    "on" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                },
            },
            "access" : "readwrite",
            "description" :
                """Status of loop power
0=Off, 1=On""",
        }, # scalar
        "npRelHumidity" : {
            "nodetype" : "node",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8400",
        }, # node
        "npRelHumSensor" : {
            "nodetype" : "node",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8400.2",
        }, # node
        "npRelHumSensorValueH" : {
            "nodetype" : "scalar",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8400.2.2",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "100"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "100"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Relative humidity value, %""",
        }, # scalar
        "npRelHumSensorStatus" : {
            "nodetype" : "scalar",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8400.2.3",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "error" : {
                        "nodetype" : "namednumber",
                        "number" : "0"
                    },
                    "ok" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Status of the Rel.Humidity Sensor One
0=Normal, 1=Error or Sensor isn't connected""",
        }, # scalar
        "npRelHumSensorValueT" : {
            "nodetype" : "scalar",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8400.2.4",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "-60",
                        "max" : "200"
                    },
                    ],
                    "range" : {
                        "min" : "-60",
                        "max" : "200"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Sensor temperature, deg.C""",
        }, # scalar
        "npRelHumSensorStatusH" : {
            "nodetype" : "scalar",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8400.2.5",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "sensorFailed" : {
                        "nodetype" : "namednumber",
                        "number" : "0"
                    },
                    "belowSafeRange" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "inSafeRange" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                    "aboveSafeRange" : {
                        "nodetype" : "namednumber",
                        "number" : "3"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Status of Relative Humiduty""",
        }, # scalar
        "npRelHumSafeRangeHigh" : {
            "nodetype" : "scalar",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8400.2.7",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "100"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "100"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Relative Humidity safe range, top margin, %RH""",
        }, # scalar
        "npRelHumSafeRangeLow" : {
            "nodetype" : "scalar",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8400.2.8",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "100"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "100"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Relative Humidity safe range, bottom margin, %RH""",
        }, # scalar
        "npRelHumSensorValueT100" : {
            "nodetype" : "scalar",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8400.2.9",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Integer32"},
            },
            "access" : "readonly",
            "description" :
                """Sensor temperature, deg.C * 100 (fixed point two decimal places)
Used to get access to the fractional part of T value""",
        }, # scalar
        "npThermo" : {
            "nodetype" : "node",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8800",
        }, # node
        "npThermoTable" : {
            "nodetype" : "table",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8800.1",
            "status" : "current",
            "description" :
                """Thermo Sensors Table""",
        }, # table
        "npThermoEntry" : {
            "nodetype" : "row",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8800.1.1",
            "status" : "current",
            "linkage" : [
                "npThermoSensorN",
            ],
            "description" :
                """Thermo Sensors Table Row""",
        }, # row
        "npThermoSensorN" : {
            "nodetype" : "column",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8800.1.1.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "1",
                        "max" : "8"
                    },
                    ],
                    "range" : {
                        "min" : "1",
                        "max" : "8"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """The id of temperature sensor, 1 to 8""",
        }, # column
        "npThermoValue" : {
            "nodetype" : "column",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8800.1.1.2",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "-60",
                        "max" : "280"
                    },
                    ],
                    "range" : {
                        "min" : "-60",
                        "max" : "280"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Temperature, deg.C""",
        }, # column
        "npThermoStatus" : {
            "nodetype" : "column",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8800.1.1.3",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "failed" : {
                        "nodetype" : "namednumber",
                        "number" : "0"
                    },
                    "low" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "norm" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                    "high" : {
                        "nodetype" : "namednumber",
                        "number" : "3"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Temperature status (0=fault, 1=underheat, 2=normal, 3=overheat)""",
        }, # column
        "npThermoLow" : {
            "nodetype" : "column",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8800.1.1.4",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "-60",
                        "max" : "280"
                    },
                    ],
                    "range" : {
                        "min" : "-60",
                        "max" : "280"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Bottom margin of normal temperature range, deg.C""",
        }, # column
        "npThermoHigh" : {
            "nodetype" : "column",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8800.1.1.5",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "-60",
                        "max" : "280"
                    },
                    ],
                    "range" : {
                        "min" : "-60",
                        "max" : "280"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Top margin of normal temperature range, deg.C""",
        }, # column
        "npThermoMemo" : {
            "nodetype" : "column",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8800.1.1.6",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """T channel memo""",
        }, # column
        "npThermoTraps" : {
            "nodetype" : "node",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8800.2",
        }, # node
        "npThermoTrapPrefix" : {
            "nodetype" : "node",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8800.2.0",
        }, # node
        "npThermoTrapSensorN" : {
            "nodetype" : "scalar",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8800.2.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "1",
                        "max" : "8"
                    },
                    ],
                    "range" : {
                        "min" : "1",
                        "max" : "8"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """The id of temperature sensor, 1 to 8""",
        }, # scalar
        "npThermoTrapValue" : {
            "nodetype" : "scalar",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8800.2.2",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "-60",
                        "max" : "280"
                    },
                    ],
                    "range" : {
                        "min" : "-60",
                        "max" : "280"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Temperature, deg.C""",
        }, # scalar
        "npThermoTrapStatus" : {
            "nodetype" : "scalar",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8800.2.3",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "failed" : {
                        "nodetype" : "namednumber",
                        "number" : "0"
                    },
                    "low" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "norm" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                    "high" : {
                        "nodetype" : "namednumber",
                        "number" : "3"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Temperature status (0=fault, 1=underheat, 2=normal, 3=overheat)""",
        }, # scalar
        "npThermoTrapLow" : {
            "nodetype" : "scalar",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8800.2.4",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "-60",
                        "max" : "280"
                    },
                    ],
                    "range" : {
                        "min" : "-60",
                        "max" : "280"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Bottom margin of normal temperature range, deg.C""",
        }, # scalar
        "npThermoTrapHigh" : {
            "nodetype" : "scalar",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8800.2.5",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "-60",
                        "max" : "280"
                    },
                    ],
                    "range" : {
                        "min" : "-60",
                        "max" : "280"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Top margin of normal temperature range, deg.C""",
        }, # scalar
        "npThermoTrapMemo" : {
            "nodetype" : "scalar",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8800.2.6",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """T channel memo""",
        }, # scalar
        "npIo" : {
            "nodetype" : "node",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8900",
        }, # node
        "npIoTable" : {
            "nodetype" : "table",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8900.1",
            "status" : "current",
            "description" :
                """Digital Input/output Table""",
        }, # table
        "npIoEntry" : {
            "nodetype" : "row",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8900.1.1",
            "status" : "current",
            "linkage" : [
                "npIoLineN",
            ],
            "description" :
                """Digital Input/output Table Row""",
        }, # row
        "npIoLineN" : {
            "nodetype" : "column",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8900.1.1.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "1",
                        "max" : "16"
                    },
                    ],
                    "range" : {
                        "min" : "1",
                        "max" : "16"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Number of IO line, from 1 to max supported""",
        }, # column
        "npIoLevelIn" : {
            "nodetype" : "column",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8900.1.1.2",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "1"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "1"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Input level, 0 or 1""",
        }, # column
        "npIoLevelOut" : {
            "nodetype" : "column",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8900.1.1.3",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Integer32"},
            },
            "access" : "readwrite",
            "description" :
                """Output level, 0 or 1.
Write -1 to flip output.""",
        }, # column
        "npIoMemo" : {
            "nodetype" : "column",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8900.1.1.6",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """IO line memo""",
        }, # column
        "npIoPulseCounter" : {
            "nodetype" : "column",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8900.1.1.9",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-SMI", "name" : "Counter32"},
            },
            "access" : "readwrite",
            "description" :
                """Pulse Counter on IO input line (counts positive fronts)
Write 0 to reset.""",
        }, # column
        "npIoSinglePulseDuration" : {
            "nodetype" : "column",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8900.1.1.12",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "100",
                        "max" : "25500"
                    },
                    ],
                    "range" : {
                        "min" : "100",
                        "max" : "25500"
                    },
                },
            },
            "access" : "readwrite",
            "description" :
                """Set duration of single pulse on IO output line,
100ms to 25500ms, min. step is 100ms""",
        }, # column
        "npIoSinglePulseStart" : {
            "nodetype" : "column",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8900.1.1.13",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Integer32"},
            },
            "access" : "readwrite",
            "description" :
                """Write 1 to start single pulse on IO output. 
Output will be inverted for time, specified by npIoSinglePulseDuration""",
        }, # column
        "npIoTraps" : {
            "nodetype" : "node",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8900.2",
        }, # node
        "npIoTrapPrefix" : {
            "nodetype" : "node",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8900.2.0",
        }, # node
        "npIoTrapLineN" : {
            "nodetype" : "scalar",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8900.2.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "1",
                        "max" : "16"
                    },
                    ],
                    "range" : {
                        "min" : "1",
                        "max" : "16"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Trap data, Number of IO line""",
        }, # scalar
        "npIoTrapLevelIn" : {
            "nodetype" : "scalar",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8900.2.2",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "1"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "1"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Trap data, new Input level, 0 or 1""",
        }, # scalar
        "npIoTrapMemo" : {
            "nodetype" : "scalar",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8900.2.6",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """Trap data, IO line memo""",
        }, # scalar
    }, # nodes

    "notifications" : {
        "npCurLoopTrap" : {
            "nodetype" : "notification",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8300.2.0.1",
            "status" : "current",
            "objects" : {
                "npCurLoopTrapN" : {
                    "nodetype" : "object",
                    "module" : "DKSF-60-4-X-X-X"
                },
                "npCurLoopTrapStatus" : {
                    "nodetype" : "object",
                    "module" : "DKSF-60-4-X-X-X"
                },
                "npCurLoopTrapI" : {
                    "nodetype" : "object",
                    "module" : "DKSF-60-4-X-X-X"
                },
                "npCurLoopTrapV" : {
                    "nodetype" : "object",
                    "module" : "DKSF-60-4-X-X-X"
                },
                "npCurLoopTrapR" : {
                    "nodetype" : "object",
                    "module" : "DKSF-60-4-X-X-X"
                },
                "npCurLoopTrapPower" : {
                    "nodetype" : "object",
                    "module" : "DKSF-60-4-X-X-X"
                },
            },
            "description" :
                """Status of current loop N has changed!""",
        }, # notification
        "npThermoTrap" : {
            "nodetype" : "notification",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8800.2.0.1",
            "status" : "current",
            "objects" : {
                "npThermoTrapSensorN" : {
                    "nodetype" : "object",
                    "module" : "DKSF-60-4-X-X-X"
                },
                "npThermoTrapValue" : {
                    "nodetype" : "object",
                    "module" : "DKSF-60-4-X-X-X"
                },
                "npThermoTrapStatus" : {
                    "nodetype" : "object",
                    "module" : "DKSF-60-4-X-X-X"
                },
                "npThermoTrapLow" : {
                    "nodetype" : "object",
                    "module" : "DKSF-60-4-X-X-X"
                },
                "npThermoTrapHigh" : {
                    "nodetype" : "object",
                    "module" : "DKSF-60-4-X-X-X"
                },
                "npThermoTrapMemo" : {
                    "nodetype" : "object",
                    "module" : "DKSF-60-4-X-X-X"
                },
            },
            "description" :
                """Status of Thermo sensor is changed (crossing of normal temp. range)""",
        }, # notification
        "npIoTrap" : {
            "nodetype" : "notification",
            "moduleName" : "DKSF-60-4-X-X-X",
            "oid" : "1.3.6.1.4.1.25728.8900.2.0.1",
            "status" : "current",
            "objects" : {
                "npIoTrapLineN" : {
                    "nodetype" : "object",
                    "module" : "DKSF-60-4-X-X-X"
                },
                "npIoTrapLevelIn" : {
                    "nodetype" : "object",
                    "module" : "DKSF-60-4-X-X-X"
                },
                "npIoTrapMemo" : {
                    "nodetype" : "object",
                    "module" : "DKSF-60-4-X-X-X"
                },
            },
            "description" :
                """Input state of IO line is changed""",
        }, # notification
    }, # notifications

}
